### ISSUE TITLE
Open in CodeChic context menu not working

### ISSUE THREAD

**Issue by RubenDijkhof** [RookieGz/CodeSnap#1]
When selecting a code snippet withing VSC, right clicking and then selecting Open in CodeChic, the webbrowser opens the CodeChic website. but doesn't show the selected text from within VSC. Instead it displays the deafult getData function placeholder in JavaScript.

**Comment by RookieGz** [comment]
Hi  @RubenDijkhof

Thank you for reporting this issue and bringing it to our attention! 🙌

We’ve identified the root cause of the problem, and it has been resolved in the latest release. 🎉 Please update your extension to version 0.0.4, and you should see the selected text from VS Code correctly displayed on the CodeChic website.

**Comment by RubenDijkhof** [comment]
@RookieGz Thanks for fixing and letting me know! Much appreciated!
